### PR TITLE
New service

### PR DESCRIPTION
**Pull request by bubadev**
New service in "online phone number"

### CODE REVIEW

**Comment by AnonyPla** [comment]
It looks like they're not accepting XMR or Cash payments?

**Comment by bubadev** [comment]
They support popular cryptocurrencies, which provides anonymity

**Review by AnonyPla — CHANGES_REQUESTED** [review]
Could provide proof they accept Monero/XMR or Cash payments? (Screenshot maybe?)

**Comment by bubadev** [comment]
They do not support Monero and cash, I pointed out this feature. But they do support bitcoin, for example. I want to add them to the list called "Not accepting Monero but accepting mainstream cryptocurrencies (less recommended):"

**Comment by AnonyPla** [comment]
Oh yes indeed, but I'm removing that section in the next release leaving only the services accepting XMR as a minimum requirement. There are too many services accepting mainstream crypto anyway and the list would have to be endless to be fair. **So the others in there will be removed as well. Sorry. Closing request.**

**Pull request closed without merging**
