### PR TITLE
Wording: unify usage of ECH and eSNI to ECH/eSNI

### PR DESCRIPTION
**Pull request by Bost**

### CODE REVIEW

**Comment by AnonyPla** [comment]
Why? They're not the same thing anymore

**Comment by AnonyPla** [comment]
Denied

**Comment by Bost** [comment]
> Why? They're not the same thing anymore

To me, if the text says "ECH (formerly eSNI)", that means "same content, only the name is different". And then the "ECH/eSNI" I read is as an extra hint at the act of renaming.

Is my interpretation correct or is it not correct?

**Comment by AnonyPla** [comment]
Indeed, ECH is now what is to replace eSNI ... technically not the same thing but technically the successor within the TLS 1.3 protocol if I'm not mistaken.

I would refer to this Cloudflare blog [article](https://blog.cloudflare.com/encrypted-client-hello/) which I think explains it best with the most convenient to read details. Also accessible here on [archive.org](https://web.archive.org/web/blog.cloudflare.com/encrypted-client-hello/) if you prefer to avoid Cloudflare. 

That of course is my interpretation. So eSNI was first. ECH is now the "successor" but clearly not the same thing technically.

WDYT?

**Pull request closed without merging**
