### PR TITLE
Updated link to the Telegram transparency report channel

### PR DESCRIPTION
**Pull request by soxoj**
Used web version preview link instead of app redirect link

### CODE REVIEW

**Comment by AnonyPla** [comment]
The link is empty to me no matter what actually, there is no report. Is that the case for you too?

**Comment by soxoj** [comment]
Yeah, the Telegram transparency report channel is empty actually. But now don't have to install a client to check it. :)

**Comment by AnonyPla** [comment]
So wait ... this is completely useless?

**Comment by AnonyPla** [comment]
No I'm kinda inclined to leave the link and just say "But there are none in there it seems"

**Review by AnonyPla — APPROVED** [review]

**Comment by AnonyPla** [comment]
idiot me

**Comment by AnonyPla** [comment]
Since I fucked up I'll instead update it in the next release instead

**Pull request merged**
